#Universidad Internacional de la Rioja
#Contenedores
#Elias Muñoz Primero

#Importación de una imagen PHP con Apache
FROM php:7.4-apache

#Se copia el archivo index a la ruta default de Apache
COPY index.php /var/www/html

#Se expone el puerto 80
EXPOSE 80